services:
  nginx:
    restart: unless-stopped
    image: amihsan/quiz-frontend:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./frontend/.env
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./docker/frontend/templates:/etc/nginx/templates

    depends_on:
      - backend

  backend:
    restart: unless-stopped
    image: amihsan/quiz-backend:latest
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done'"
