version: "3"

services:
  # Frontend service (React app served by Nginx)
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    env_file:
      - ./frontend/.env # Load environment variables from .env file
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
    depends_on:
      - backend # Ensure backend is started before frontend

  # Backend service (Flask app)
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env # Load environment variables from .env file
