version: "3"

services:
  # React Frontend Service via nginx
  nginx:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/quiz-frontend
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./frontend/.env
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - backend
  # Flask Backend Service
  backend:
    restart: unless-stopped
    image: ${DOCKER_USERNAME}/quiz-backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env

  # Certbot for SSL Certificates
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
# version: "3"

# services:
#   # React Frontend Service via nginx
#   nginx:
#     restart: unless-stopped
#     build:
#       context: .
#       dockerfile: ./docker/frontend/Dockerfile
#     ports:
#       - 80:80
#       - 443:443
#     env_file:
#       - ./frontend/.env
#     volumes:
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#       - ./nginx/templates:/etc/nginx/templates
#     depends_on:
#       - backend
#   # Flask Backend Service
#   backend:
#     restart: unless-stopped
#     build:
#       context: .
#       dockerfile: ./docker/backend/Dockerfile
#     ports:
#       - 5000:5000
#     env_file:
#       - ./backend/.env

#   # Certbot for SSL Certificates
#   certbot:
#     image: certbot/certbot
#     restart: unless-stopped
#     volumes:
#       - ./certbot/conf:/etc/letsencrypt
#       - ./certbot/www:/var/www/certbot
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

