version: "3.7"

services:
  # React Frontend Service via nginx
  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - ./frontend/.env

  # Flask Backend Service
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env

  # Certbot for SSL Certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
# version: "3"

# services:
#   nginx:
#     restart: unless-stopped
#     build:
#       context: .
#       dockerfile: ./docker/nginx/Dockerfile
#     ports:
#       - 80:80
#     env_file:
#       - ./frontend/.env
#     depends_on:
#       - backend

#   backend:
#     restart: unless-stopped
#     build:
#       context: .
#       dockerfile: ./docker/backend/Dockerfile
#     ports:
#       - 5000:5000
#     env_file:
#       - ./backend/.env
