# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: amihsan/quiz-frontend
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-certbot-conf
          mountPath: /etc/letsencrypt
        - name: nginx-certbot-www
          mountPath: /var/www/certbot
        - name: nginx-templates
          mountPath: /etc/nginx/templates

      volumes:
      - name: nginx-certbot-conf
        hostPath:
          path: docker/nginx/certbot/conf
      - name: nginx-certbot-www
        hostPath:
          path: docker/nginx/certbot/www
      - name: nginx-templates
        hostPath:
          path: docker/nginx/templates

# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  selector:
    app: nginx
